### ISSUE TITLE
TODO's Examples

### ISSUE THREAD

**Issue by prisae** [emsig/emg3d-gallery#6]
- [ ] Set-up automatic deploy through GHA -> gh-pages

- [x] Replaced deprecated meshing functions (`get_hx_h0` etc)
- [x] Update TDEM examples
- [ ] Add mesh converging test example
- [ ] Add examples using all sources and receivers
